#pragma once

#define NEGATIVE_INFINITY -96.0f
#define MAX_DECIBELS 18.0f

#define FRAMES_PER_SECOND 60
#define AVG_TIME_SECONDS 1

#define TICKS_INTERVAL 6

#define MONO_METER_WIDTH 15
#define STEREO_METER_SCALE_WIDTH 25

#define MONO_METER_Y_MARGIN 10
#define MONO_METER_COMPONENT_SPACING 5

#define SCALE_TEXT_SIZE 10.0f
#define METER_LABEL_TEXT_SIZE 14.0f

#define STEREO_METER_MARGIN 5
